---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
    tenant: vite
spec:
  replicas: 1
  selector:
    matchLabels:
        app: example
  template:
    metadata:
      labels:
        app: example
        tenant: vite
    spec:
      imagePullSecrets:
        - name: gitea-auth
      containers:
        - name: example
          image: "gitea.pixelparasol.com/pixel-parasol/hostel-fish/example:latest"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap