---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: seattle
    tenant: {{ .Values.system }}
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html =404;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }