---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example
    tenant: vite
spec:
  type: ClusterIP
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http