image:
  repository: gitea.pixelparasol.com/pixel-parasol/hostel-fish/seattle
  tag: "latest"
  imagePullPolicy: "Always"
  imagePullSecrets: "gitea-auth"

ingress:
  domain: example.demo.pixelparasol.com
  path: /example
  className: "nginx"
  port: 80

service:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http